---
- name: Add prosody.im apt signing key
  apt_key: url=https://prosody.im/files/prosody-debian-packages.key state=present

- name: Add prosody.im stable repo
  apt_repository: repo="deb http://packages.prosody.im/debian {{ ansible_distribution_release }} main" state=present

- name: Install prosody and deps
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - prosody
    - lua-zlib # for compression

- name: Copy TLS cert
  copy: { dest: "{{ prosody_conf_dir }}/certs/{{ xmpp_domain_name }}.crt", content: "{{ xmpp_tls_cert }}", mode: 0600, owner: 'prosody', group: 'prosody' }
  notify:
    - reload prosody

- name: Copy TLS key
  copy: { dest: "{{ prosody_conf_dir }}/certs/{{ xmpp_domain_name }}.key", content: "{{ xmpp_tls_key }}", mode: 0600, owner: 'prosody', group: 'prosody' }
  notify:
    - reload prosody

- name: Generate 2048-bit dhparam
  command: openssl dhparam -out dhparam-2048.pem 2048 chdir={{ prosody_conf_dir }}/certs creates=dhparam-2048.pem
  notify:
    - reload prosody

- name: Copy prosody config
  template: src={{ prosody_conf_file }}.j2 dest={{ prosody_conf_dir }}/{{ prosody_conf_file }} mode=0655 owner=root group=root
  notify:
    - reload prosody

- name: Start & enable prosody service
  service: name=prosody state=started enabled=yes

# vim: set ts=2 sw=2:
