---
- name: Install php5-fpm and deps 
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php5-fpm
    # for WordPress
    - php5-mysql
    - php5-gd
    - php5-curl
  tags: php5-fpm

- name: Copy php5-fpm pool config
  template: src=pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ item.nginx_domain_name }}.conf owner=root group=root mode=0644
  with_items: nginx_vhosts
  when: nginx_vhosts is defined
  notify: restart php5-fpm
  tags: php5-fpm

- name: Copy php5-fpm pool config
  template: src=pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ item.nginx_domain_name }}.conf owner=root group=root mode=0644
  with_items: nginx_tls_vhosts
  when: nginx_tls_vhosts is defined
  notify: restart php5-fpm
  tags: php5-fpm

# re-configure php.ini
- name: Update php.ini
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini owner=root group=root mode=0644
  notify: restart php5-fpm
  tags: php5-fpm

# vim: set ts=2 sw=2:
